name: CI Pipeline - Raghav Soni

on:
  push:
    branches:
      - main

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - name: Run pytest with PYTHONPATH
        run: |
          echo "PYTHONPATH is $(pwd)"
          export PYTHONPATH="$(pwd)"
          python -m pytest tests/

  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: |
          export PYTHONPATH="$(pwd)"
          python src/train.py
          python src/quantize.py

  build-and-test-container:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t mlops-raghav .
      - run: docker run --rm mlops-raghav
